### ISSUE TITLE
How to configure JLCPCB order

### ISSUE THREAD

**Issue by ProjectInitiative** [zappanaut/usb-atx-ctrl#1]
I am looking to place an order through JLCPCB. In https://github.com/pikvm/pikvm/issues/433 it was mentioned that costs were low. Is that only low if you solder everything yourself? I am not sure if I was inputting information correctly, but with assembly costs, it ended up being close to $70 USD. 

Am I missing something? 
Thanks
![Screenshot from 2023-01-28 18-33-55](https://user-images.githubusercontent.com/6314611/215297532-78c53023-bbac-4089-909f-82e319b8a793.png)

**Comment by zappanaut** [comment]
Costs should be at around $10 (depending on your location and shipping costs) only for the PCBs without assembly and stencil. You can see in the charge details that the bare PCBs are just $2. Unfortunately I never used the assembly service, so I fear I am of little help regarding that.
PS: Just for the PCBs you can stick with the default options and maybe choose a different PCB color or surface finish.
For shipping to Germany I chose EuroPacket.

<img width="1047" alt="Screenshot_20230129_020954" src="https://user-images.githubusercontent.com/33423139/215298570-1b7b274f-96fc-43a6-add4-b52f332cc34c.png">

**Comment by ProjectInitiative** [comment]
Gotcha, I might try my hand at soldering my own components. Admittedly I am not much of an electrical engineer, how does one solder the RP2040 zero to the PCB? With a header?

**Comment by zappanaut** [comment]
Yes, the RP2040-Zero is soldered down with pin headers.

**Comment by SchoolGuy** [comment]
@ProjectInitiative Did you use the assembly service in the end? I am in a similar situation as you are. If yes can you do a small writeup on how to actually add components (Raspi, ICs, ...)?

**Comment by ProjectInitiative** [comment]
@SchoolGuy I did not end up going through with the purchase. Assembly on a two sided board was too high (~$70 without the components). JLCPCB also didn't offer/have all of the needed components. When I tried to source some of the relays, it ended up being more expensive than to buy some blicube ATX adapters and build a new controller off of a Pico. If you want to see what I did: https://github.com/ProjectInitiative/pikvm-atx

@zappanaut's solution is really clean though if you went that route, just needs some hands on soldering in my opinion. :)

**Comment by zappanaut** [comment]
Last time I checked they had suitable and inexpensive PhotoMOS relays in stock. If someone wants to give it a try, I am happy to assist with picking the right parts.
@SchoolGuy In any case you have to buy and solder the RP2040-Zero yourself.

**Comment by SchoolGuy** [comment]
@zappanaut Well if I manage to solder that one on by myself, I guess that the other components are also possible to solder on by myself? I am sadly not able to wield flux correctly (last time I tried I messed up the board and components I wanted to solder on) and thus I was looking to get a "plug and play" solution. The magic of hardware is not my strength. Are there any options for such a board like yours? Assembling sth like the PiKVM I was able to do but luckily the header was pre-produced and thus it was only a little bit of plugging the correct things into the correct jacks.

**Comment by zappanaut** [comment]
@SchoolGuy for sure you need a little bit of practice. You may also want to use lead solder, that is way easier to handle. I deliberately chose 1206 sized parts for hand soldering. Tweezers are still necessary , though.
There is nothing wrong with using lots of flux (if it is proper flux meant for electronics and not for gutters). Simply clean the boards with 2-Propanol afterwards.
On YT there are lots of tutorials regarding soldering and I would like advice you to practice a bit with SMD soldering. And maybe a local hackerspace is also an option for you.
Regarding JLCPCB's assembly service, I think you have to send the proper bunch of production files to keep the cost down. That also means you have to assign the right JLCPCB partnumbers in the schematic, check parts orientation etc...

**Comment by SchoolGuy** [comment]
@zappanaut Thanks for the advice. I will try my best. I'll report once I have it up and running (might take a while).
